# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(920, 561)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GKbCl.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 10, 481, 501))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_2.addWidget(self.plainTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lotags = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lotags.setFont(font)
        self.lotags.setObjectName("lotags")
        self.horizontalLayout_5.addWidget(self.lotags)
        self.otags = QtWidgets.QLineEdit(self.layoutWidget)
        self.otags.setObjectName("otags")
        self.horizontalLayout_5.addWidget(self.otags)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(500, 150, 387, 218))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.r1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.r1.setText("")
        self.r1.setObjectName("r1")
        self.verticalLayout_3.addWidget(self.r1)
        self.r2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.r2.setText("")
        self.r2.setObjectName("r2")
        self.verticalLayout_3.addWidget(self.r2)
        self.r3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.r3.setText("")
        self.r3.setObjectName("r3")
        self.verticalLayout_3.addWidget(self.r3)
        self.r4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.r4.setText("")
        self.r4.setObjectName("r4")
        self.verticalLayout_3.addWidget(self.r4)
        self.r5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.r5.setText("")
        self.r5.setObjectName("r5")
        self.verticalLayout_3.addWidget(self.r5)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 10, 381, 131))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("stackoverflow-logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(500, 480, 421, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ac = QtWidgets.QPushButton(self.layoutWidget2)
        self.ac.setObjectName("ac")
        self.horizontalLayout_6.addWidget(self.ac)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.lf1 = QtWidgets.QLabel(self.centralwidget)
        self.lf1.setGeometry(QtCore.QRect(640, 460, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lf1.setFont(font)
        self.lf1.setObjectName("lf1")
        self.acl = QtWidgets.QLabel(self.centralwidget)
        self.acl.setGeometry(QtCore.QRect(520, 460, 66, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.acl.setFont(font)
        self.acl.setObjectName("acl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_9.clicked.connect(self.plainTextEdit.clear)
        self.pushButton_9.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_9.clicked.connect(self.lineEdit.clear)
        self.pushButton_9.clicked.connect(self.label_9.hide)
        self.pushButton_9.clicked.connect(self.r1.hide)
        self.pushButton_9.clicked.connect(self.r2.hide)
        self.pushButton_9.clicked.connect(self.r3.hide)
        self.pushButton_9.clicked.connect(self.r4.hide)
        self.pushButton_9.clicked.connect(self.r5.hide)
        self.pushButton_8.clicked.connect(MainWindow.close)
        self.pushButton_9.clicked.connect(self.acl.hide)
        self.pushButton_9.clicked.connect(self.lf1.hide)
        self.pushButton_9.clicked.connect(self.otags.clear)
        self.pushButton_9.clicked.connect(self.lotags.hide)
        self.pushButton_9.clicked.connect(self.otags.hide)
        self.pushButton_9.clicked.connect(self.otags.clear)
        self.ac.clicked.connect(self.acl.show)
        self.pushButton_3.clicked.connect(self.lf1.show)
        self.pushButton_4.clicked.connect(self.label_9.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "StackOverflow Application"))
        self.label.setText(_translate("MainWindow", "Title"))
        self.label_2.setText(_translate("MainWindow", "Body"))
        self.pushButton.setText(_translate("MainWindow", "Predict"))
        self.label_3.setText(_translate("MainWindow", "Tags                 "))
        self.lotags.setText(_translate("MainWindow", "Original Tags"))
        self.pushButton_4.setText(_translate("MainWindow", "Get Recommendations"))
        self.label_9.setText(_translate("MainWindow", "                       RECOMMENDATIONS"))
        self.ac.setText(_translate("MainWindow", "Get Accuracy"))
        self.pushButton_3.setText(_translate("MainWindow", "Get F1 Score"))
        self.pushButton_9.setText(_translate("MainWindow", "Clear"))
        self.pushButton_8.setText(_translate("MainWindow", "Exit"))
        self.lf1.setText(_translate("MainWindow", "F1 Score"))
        self.acl.setText(_translate("MainWindow", "Accuracy"))

